### ISSUE TITLE
[Idea] MDN Web Docs is for you

### ISSUE THREAD

**Issue by Mte90** [Mte90/mte90.github.io#21]
The idea is to create a talk to promote mdn against webschools and others

**Comment by KipOmaha** [comment]
What type of ideas did you want, I've been thinking of the same thing!

**Comment by Mte90** [comment]
Not easy because I need to uderstand before how the devs use web documentation and in that few do the plan for that talk. Usually I know that many people use w3schools for the live editor and MDN doesn't have so I need to find an alternative

**Comment by KipOmaha** [comment]
The build used kumascript...basically page scrapers and it looks like a wiki type of serving sys.

Definitely something I would definitely be willing to colab on.

**Comment by Mte90** [comment]
Probably this one is better as light talk during javascript meetup.
