### ISSUE TITLE
[Idea] Know your community members

### ISSUE THREAD

**Issue by Mte90** [Mte90/mte90.github.io#23]
The idea is a talk about profiling the members and understand why they joined etc

**Comment by KipOmaha** [comment]
I love this topic...Have you ever took a look at N3Pix profile pict as an example...

https://forum.learning.mozilla.org/u/n3pix/summary  

Do you know who General Mustafa Kemal is?

**Comment by KipOmaha** [comment]
Another example is my own profile name, which is an acronym that stands for, knowledge is power.

**Comment by Mte90** [comment]
My idea is based after my experience:

* https://discourse.mozilla-community.org/t/results-of-the-mobilizer-experiment-for-webextension-italy/16494
* https://discourse.mozilla-community.org/t/leadership-resources/16551/
* http://mte90.github.io/Talk-Coaching/

Also as speaker of CLSX and in other stuff that I do for open source.
